# Generated by Django 5.2 on 2025-04-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NanoURL",
            fields=[
                (
                    "nano_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("original_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
